---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/kubeshark version
    register: kubeshark_test_output
  - name: kubeshark version
    debug:
      msg: '{{ kubeshark_test_output.stderr }}'
