---
- name: Install andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Look for installation at {{ kubeshark_exe }}
  ansible.builtin.stat:
    path: '{{ kubeshark_exe }}'
  register: kubeshark_binary
- when: not kubeshark_binary.stat.exists
  block:
    - name: Downloading {{ kubeshark_url }} to {{ kubeshark_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ kubeshark_url }}'
        dest: '{{ kubeshark_tmp_archive }}'
        checksum: '{{ kubeshark_checksum }}'
        mode: '644'
    - name: Mkdir {{ kubeshark_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ kubeshark_install_dir }}'
        state: directory
        mode: '755'
    - name: Unarchive {{ kubeshark_tmp_archive }} into {{ kubeshark_install_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ kubeshark_tmp_archive }}'
        dest: '{{ kubeshark_install_dir }}'
        creates: '{{ kubeshark_exe }}'
  always:
    - name: Cleanup
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ kubeshark_tmp_archive }}'
        state: absent
- name: Linking {{ kubeshark_link }} to {{ kubeshark_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ kubeshark_exe }}'
    dest: '{{ kubeshark_link }}'
    state: link
